Syoung smallwisdom patch 4
Sage-Bionetworks/BridgeDocs pull request #212
Opened 2018-09-13 23:26 UTC by syoung-smallwisdom

2018-09-14 00:01 UTC, Erin-Mounts requested changes
Couple of comments/questions and a bunch of nits

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +* Keychain Sharing - The login information is saved to the keychain. Your application will need to set up a
I don't think this is true unless you're either using app extensions, or needing to peek at what's in the BridgeSDK keychain -- and I think you *wouldn't* want to do it if you publish multiple Bridge apps to the app store for different studies, because you wouldn't want them to share the stored credentials and session/reauth tokens (which aren't valid across study boundaries)...

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +**For `HealthKit` data that is required such as demographic information, this should be stored in the user's Bridge profile for use by researchers as well as for use by your application in case the u
given --> give

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +plist will overwrite any fields included in the open source version of the file. `BridgeAppExample`
overwrite --> override

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +[mPower 2](https://github.com/Sage-Bionetworks/mPower-2-iOS "mPower 2") is currently the only app that is using both phone SMS and external ID sign in. This application is structured with two target
mPower -> mPower2
mPowerTestApp -> mPower2TestApp
independ**a**ntly -> independ**e**ntly

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +It is recommended to structure your app using a "module" structure for the active tasks to facilitate using these validated tasks without requiring integration with Sage Bridge and Synapse services.
It is recommended to --> We recommend that you

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +**- TODO: syoung 09/13/2018 Continue editing**
um...

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +To add a custom active task, you will need to set up JSON files defining the task, include factory overrides for any custom steps, and include a storyboard or nib for any custom view controllers. See
mPower -> mPower2

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +To set up and use Bridge schedules and upload schemas, your view controllers will need to use a `SBAScheduleManager` instance or a `SBAReportManager` instance as the data source. See `TaskBrowserView
mPower -> mPower2

2018-09-14 00:01 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +To understand how the mapping works, you will need to go spelunking by searching out `RSDArchivable`. This is a protocol that is used to indicate which results should be archived and uploaded. For ex
"spelunking" is a most excellent word :+1:

2018-09-14 00:17 UTC, syoung-smallwisdom commented on _articles/ios_get_started.md
> +* Keychain Sharing - The login information is saved to the keychain. Your application will need to set up a
Hmm.... then why is it set up that way in mPower?

2018-09-14 00:20 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +* Keychain Sharing - The login information is saved to the keychain. Your application will need to set up a
uhhh... not sure? I may have inadvertently done that in the wrong branch when I was briefly looking at the possibility of having ProfileManager use the same keychain BridgeSDK was using.

2018-09-14 00:22 UTC, syoung-smallwisdom commented on _articles/ios_get_started.md
> +**- TODO: syoung 09/13/2018 Continue editing**
oops

Wanted to commit "progress" and GitHub was confusing me.

2018-09-14 00:22 UTC, syoung-smallwisdom commented on _articles/ios_get_started.md
> +To understand how the mapping works, you will need to go spelunking by searching out `RSDArchivable`. This is a protocol that is used to indicate which results should be archived and uploaded. For ex
;)

2018-09-14 00:25 UTC, syoung-smallwisdom commented on _articles/ios_get_started.md
> +* Keychain Sharing - The login information is saved to the keychain. Your application will need to set up a
Hmmm... So... how is the keychain set up?

Looks like BridgeSDK uses `org.sagebase.Bridge` ?

2018-09-17 16:56 UTC, Erin-Mounts approved these changes

2018-09-17 16:56 UTC, Erin-Mounts commented on _articles/ios_get_started.md
> +* Keychain Sharing - The login information is saved to the keychain. Your application will need to set up a
So, I think what this should say now is that they need to set up a shared keychain access group, and specify it in the keychainAccessGroup property of BridgeInfo, if they use or support app extensions, and that we suggest they consider doing so anyway in case they later decide to use app extensions.

2018-09-17 16:57 UTC, merged